SELECT TOP 10
    *
FROM sys.databases WITH (NOLOCK)
ORDER BY 1 DESC;

SELECT TOP 10
    *
FROM sys.tables WITH (NOLOCK)
ORDER BY 1 DESC;

SELECT TOP 10
    *
FROM GroupLocations WITH (NOLOCK)
ORDER BY 1 DESC;

SELECT TOP 10
    *
FROM EmailTemplate WITH (NOLOCK)
ORDER BY 1 DESC;

SELECT TOP 10
    *
FROM GroupPrograms WITH (NOLOCK)
ORDER BY 1 DESC;

SELECT TOP 10
    *
FROM Admin WITH (NOLOCK)
ORDER BY 1 DESC;

SELECT TOP 10
    *
FROM AccessControl WITH (NOLOCK)
ORDER BY 1 DESC;

SELECT TOP 10
    *
FROM Instances WITH (NOLOCK)
ORDER BY 1 DESC;

SELECT TOP 10
    *
FROM ConsentManagement WITH (NOLOCK)
ORDER BY 1 DESC;

SELECT TOP 10
    *
FROM RoleFeatureMaster WITH (NOLOCK)
ORDER BY 1 DESC;

SELECT TOP 10
    *
FROM IntakeQuestionnaire WITH (NOLOCK)
ORDER BY 1 DESC;

SELECT TOP 10
    *
FROM DoseSpotClinics WITH (NOLOCK)
ORDER BY 1 DESC;

SELECT TOP 10
    *
FROM RoleFunctionMaster WITH (NOLOCK)
ORDER BY 1 DESC;

SELECT TOP 10
    *
FROM DoseSpotConfiguration WITH (NOLOCK)
ORDER BY 1 DESC;

SELECT TOP 10
    *
FROM RoleMaster WITH (NOLOCK)
ORDER BY 1 DESC;

SELECT TOP 10
    *
FROM IntakeResponseOptions WITH (NOLOCK)
ORDER BY 1 DESC;

SELECT TOP 10
    *
FROM ExternalClients WITH (NOLOCK)
ORDER BY 1 DESC;

SELECT TOP 10
    *
FROM LUP_AppoinmentStatus WITH (NOLOCK)
ORDER BY 1 DESC;

SELECT TOP 10
    *
FROM Groups WITH (NOLOCK)
ORDER BY 1 DESC;

SELECT TOP 10
    *
FROM LUP_ConsultationEndTypes WITH (NOLOCK)
ORDER BY 1 DESC;

SELECT TOP 10
    *
FROM LUP_ConsultationTypes WITH (NOLOCK)
ORDER BY 1 DESC;

SELECT TOP 10
    *
FROM LUP_DocumentTypes WITH (NOLOCK)
ORDER BY 1 DESC;

SELECT TOP 10
    *
FROM IntakeQuestions WITH (NOLOCK)
ORDER BY 1 DESC;

SELECT TOP 10
    *
FROM LUP_Genders WITH (NOLOCK)
ORDER BY 1 DESC;

SELECT TOP 10
    *
FROM LUP_FamilyMedicalHistory WITH (NOLOCK)
ORDER BY 1 DESC;

SELECT TOP 10
    *
FROM sysdiagrams WITH (NOLOCK)
ORDER BY 1 DESC;

SELECT TOP 10
    *
FROM LUP_PatientsSurgeryDetails WITH (NOLOCK)
ORDER BY 1 DESC;

SELECT TOP 10
    *
FROM LUP_ConsentTypes WITH (NOLOCK)
ORDER BY 1 DESC;

SELECT TOP 10
    *
FROM Lup_Allergies WITH (NOLOCK)
ORDER BY 1 DESC;

SELECT TOP 10
    *
FROM LUP_CancellationReasons WITH (NOLOCK)
ORDER BY 1 DESC;

SELECT TOP 10
    *
FROM LUP_ContactTypes WITH (NOLOCK)
ORDER BY 1 DESC;

SELECT TOP 10
    *
FROM LUP_QuestionTypes WITH (NOLOCK)
ORDER BY 1 DESC;

SELECT TOP 10
    *
FROM LUP_Languages WITH (NOLOCK)
ORDER BY 1 DESC;

SELECT TOP 10
    *
FROM LUP_QueueDismissReasons WITH (NOLOCK)
ORDER BY 1 DESC;

SELECT TOP 10
    *
FROM LUP_Medications WITH (NOLOCK)
ORDER BY 1 DESC;

SELECT TOP 10
    *
FROM LUP_ProductTypes WITH (NOLOCK)
ORDER BY 1 DESC;

SELECT TOP 10
    *
FROM LUP_States WITH (NOLOCK)
ORDER BY 1 DESC;

SELECT TOP 10
    *
FROM LUP_ProgramTypes WITH (NOLOCK)
ORDER BY 1 DESC;

SELECT TOP 10
    *
FROM LUP_Status WITH (NOLOCK)
ORDER BY 1 DESC;

SELECT TOP 10
    *
FROM LUP_QuestionCategories WITH (NOLOCK)
ORDER BY 1 DESC;

SELECT TOP 10
    *
FROM LUP_Timezones WITH (NOLOCK)
ORDER BY 1 DESC;

SELECT TOP 10
    *
FROM LUP_ReasonsForVisit WITH (NOLOCK)
ORDER BY 1 DESC;

SELECT TOP 10
    *
FROM LUP_VerificationTypes WITH (NOLOCK)
ORDER BY 1 DESC;

SELECT TOP 10
    *
FROM LUP_Suffix WITH (NOLOCK)
ORDER BY 1 DESC;

SELECT TOP 10
    *
FROM MedicalCodes WITH (NOLOCK)
ORDER BY 1 DESC;

SELECT TOP 10
    *
FROM Networks WITH (NOLOCK)
ORDER BY 1 DESC;

SELECT TOP 10
    *
FROM Products WITH (NOLOCK)
ORDER BY 1 DESC;

SELECT TOP 10
    *
FROM ProgramNetworks WITH (NOLOCK)
ORDER BY 1 DESC;

SELECT TOP 10
    *
FROM Specialities WITH (NOLOCK)
ORDER BY 1 DESC;

SELECT TOP 10
    *
FROM ProgramTranslations WITH (NOLOCK)
ORDER BY 1 DESC;

SELECT TOP 10
    *
FROM UserLoginDetails WITH (NOLOCK)
ORDER BY 1 DESC;

SELECT TOP 10
    *
FROM ProviderFees WITH (NOLOCK)
ORDER BY 1 DESC;

SELECT TOP 10
    *
FROM RoleBasedMenu WITH (NOLOCK)
ORDER BY 1 DESC;

SELECT TOP 10
    *
FROM ScoreThreshold WITH (NOLOCK)
ORDER BY 1 DESC;

SELECT TOP 10
    *
FROM RoleBasedSubMenu WITH (NOLOCK)
ORDER BY 1 DESC;

SELECT TOP 10
    *
FROM SubSpecialities WITH (NOLOCK)
ORDER BY 1 DESC;

SELECT TOP 10
    *
FROM LUP_AppointmentDismissalReasons WITH (NOLOCK)
ORDER BY 1 DESC;

SELECT TOP 10
    *
FROM Programs WITH (NOLOCK)
ORDER BY 1 DESC;

SELECT TOP 10
    *
FROM RoleBasedUIControls WITH (NOLOCK)
ORDER BY 1 DESC;

SELECT TOP 10
    *
FROM LUP_FamilyMembers WITH (NOLOCK)
ORDER BY 1 DESC;

SELECT TOP 10
    *
FROM ProgramTypeRules WITH (NOLOCK)
ORDER BY 1 DESC;

SELECT TOP 10
    *
FROM StateWiseConsentAgeRule WITH (NOLOCK)
ORDER BY 1 DESC;

SELECT TOP 10
    *
FROM LUP_RaceEthnicity WITH (NOLOCK)
ORDER BY 1 DESC;

SELECT TOP 10
    *
FROM LUP_MedicalConditions WITH (NOLOCK)
ORDER BY 1 DESC;

SELECT TOP 10
    *
FROM DoseSpotEvents WITH (NOLOCK)
ORDER BY 1 DESC;

SELECT TOP 10
    *
FROM TimerSetting WITH (NOLOCK)
ORDER BY 1 DESC;

SELECT TOP 10
    *
FROM Clients WITH (NOLOCK)
ORDER BY 1 DESC;

SELECT TOP 10
    *
FROM CryptographyAsymmetricKeys WITH (NOLOCK)
ORDER BY 1 DESC;

SELECT TOP 10
    *
FROM LUP_Relationship WITH (NOLOCK)
ORDER BY 1 DESC;

SELECT TOP 10
    *
FROM FollowupQuestions WITH (NOLOCK)
ORDER BY 1 DESC;

SELECT TOP 10
    *
FROM GroupBranding WITH (NOLOCK)
ORDER BY 1 DESC;

SELECT TOP 10
    *
FROM LUP_ProviderLicenseStatus WITH (NOLOCK)
ORDER BY 1 DESC;