SELECT TOP 10
    *
FROM ProviderRegistrations WITH (NOLOCK)
ORDER BY 1 DESC;

SELECT TOP 10
    *
FROM Addressess WITH (NOLOCK)
ORDER BY 1 DESC;

SELECT TOP 10
    *
FROM LUP_Specialities WITH (NOLOCK)
ORDER BY 1 DESC;

SELECT TOP 10
    *
FROM ProviderDocuments WITH (NOLOCK)
ORDER BY 1 DESC;

SELECT TOP 10
    *
FROM Providers WITH (NOLOCK)
ORDER BY 1 DESC;

SELECT TOP 10
    *
FROM DialCareProvidersBulkUpload WITH (NOLOCK)
ORDER BY 1 DESC;

SELECT TOP 10
    *
FROM GroupLocation WITH (NOLOCK)
ORDER BY 1 DESC;

SELECT TOP 10
    *
FROM LUP_Languages WITH (NOLOCK)
ORDER BY 1 DESC;

SELECT TOP 10
    *
FROM sysdiagrams WITH (NOLOCK)
ORDER BY 1 DESC;

SELECT TOP 10
    *
FROM UserLoginDetails WITH (NOLOCK)
ORDER BY 1 DESC;

SELECT TOP 10
    *
FROM Academics WITH (NOLOCK)
ORDER BY 1 DESC;

SELECT TOP 10
    *
FROM AppointmentSlots WITH (NOLOCK)
ORDER BY 1 DESC;

SELECT TOP 10
    *
FROM Licenses WITH (NOLOCK)
ORDER BY 1 DESC;

SELECT TOP 10
    *
FROM LUP_DocumentTypes WITH (NOLOCK)
ORDER BY 1 DESC;

SELECT TOP 10
    *
FROM LUP_RecurrenceTypes WITH (NOLOCK)
ORDER BY 1 DESC;

SELECT TOP 10
    *
FROM LUP_SubSpecialities WITH (NOLOCK)
ORDER BY 1 DESC;

SELECT TOP 10
    *
FROM Notes WITH (NOLOCK)
ORDER BY 1 DESC;

SELECT TOP 10
    *
FROM Member WITH (NOLOCK)
ORDER BY 1 DESC;

SELECT TOP 10
    *
FROM ProviderNetworks WITH (NOLOCK)
ORDER BY 1 DESC;

SELECT TOP 10
    *
FROM ProviderSubSpecialities WITH (NOLOCK)
ORDER BY 1 DESC;

SELECT TOP 10
    *
FROM RecurringSchedules WITH (NOLOCK)
ORDER BY 1 DESC;

SELECT TOP 10
    *
FROM Schedules WITH (NOLOCK)
ORDER BY 1 DESC;