import "../English/MemberRegistered/MemberRegisteredTest.cy";
import "../English/Verification/VerificationTest.cy";
import "../English/ForgotPassword/ForgotPassword.cy";
import "../English/Login/Login.cy";
import "../English/FileManagment/FileUploadTest.cy";
import "../English/StudentTest/StudentRegistration.cy";
import "../English/Patient/PatientRegistration.cy";
import "../English/UpcomingVirtualVisit/UpcomingVirtualVisitTest.cy";
import "../English/MyAccount/ContactInfoTest.cy";
import "../English/RequestVirtualVisit/RequestVirtualVisit.cy";
import "../English/VirtualVet/VirtualVetTest.cy";
import "../English/EnterWaitingRoom/EnterWaitingRoom.cy";
// import "../Spanish/Verification/VerificationTest.cy";
// import "../Spanish/Student/StudentTest.cy";
// import "../Spanish/FileManagment/FileUploadTest.cy";
// import "../Spanish/MyAccount/MyAccount.cy";
// import "../Spanish/RequestVirtualVisit/RequestVirtualVisitTest.cy";
// import "../Spanish/MemberRegistered/MemberRegisteredTest.cy";
// import "../Spanish/VirtualVet/VirtualVetTest.cy";
// import "../Spanish/EnterWaitingRoom/EnterWaitingRoom.cy";
